spring:
  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


  jpa:
    show-sql: true

example:
  property: "I AM IN THE DEFAULT"

server:
  port: 9091


